apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  type: {{ .Values.products.service.type }}
  ports:
    - port: {{ .Values.products.service.port }}
      targetPort: {{ .Values.products.service.port }}
  selector:
    app: {{ .Release.Name }}-products
