apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  type: {{ .Values.users.service.type }}
  ports:
    - port: {{ .Values.users.service.port }}
      targetPort: {{ .Values.users.service.port }}
  selector:
    app: {{ .Release.Name }}-users
